# Hermes local browser — persistent Chromium + CDP for agent automation.
#
# Why host-level (not apt inside the Ubuntu container):
# - Profile + binary survive container image refresh
# - Host network namespace matches Hermes (--network=host) → agent uses
#   http://127.0.0.1:9222 without extra docker publish
# - Egress is the NAS home WAN (Starlink here), not a Browserless DC pool
#
# This is NOT a silver bullet for AXS/Cloudflare. Cold automation profiles still
# get challenged. Value is:
# 1) sticky cookies / localStorage after a human warm-up (xrdp or hybrid handoff)
# 2) same residential-ish egress as the household
# 3) CDP attach from Hermes without your laptop Chrome
#
# Hybrid captcha handoff:
# agent drives CDP → hits challenge → screenshots to Telegram → you solve via
# xrdp on the same profile OR reply "done" after solving on a shared session.
{
  lib,
  pkgs,
  ...
}:
let
  profileDir = "/var/lib/hermes/browser-profile";
  cdpPort = 9222;
  displayNum = "99";
  display = ":${displayNum}";
  # Bind loopback only — never expose CDP on LAN/WAN.
  cdpAddr = "127.0.0.1";
in
{
  environment.systemPackages = [
    pkgs.chromium
    pkgs.xorg.xvfb
    (pkgs.writeShellScriptBin "hermes-browser-status" ''
      set -euo pipefail
      echo "profile: ${profileDir}"
      echo "cdp:     http://${cdpAddr}:${toString cdpPort}"
      if ${pkgs.curl}/bin/curl -fsS --max-time 2 "http://${cdpAddr}:${toString cdpPort}/json/version" ; then
        echo
        echo "status:  up"
      else
        echo "status:  down (is hermes-browser.service running?)"
        ${pkgs.systemd}/bin/systemctl --no-pager -l status hermes-browser.service | head -20 || true
        exit 1
      fi
    '')
  ];

  systemd.tmpfiles.rules = [
    "d ${profileDir} 0750 hermes hermes - -"
    "d /var/lib/hermes/browser-logs 0750 hermes hermes - -"
    # Ensure env file exists before hermes-agent starts (overwritten by oneshot).
    "f /run/hermes-browser.env 0640 hermes hermes - "
  ];

  # Env file merged into Hermes (container + host CLI share host network).
  systemd.services.hermes-browser-env = {
    description = "Write Hermes browser CDP env";
    wantedBy = [ "multi-user.target" ];
    before = [ "hermes-agent.service" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      umask 027
      cat > /run/hermes-browser.env <<'EOF'
# Auto-generated by hermes-browser.nix — do not edit
BU_CDP_URL=http://${cdpAddr}:${toString cdpPort}
HERMES_BROWSER_CDP_URL=http://${cdpAddr}:${toString cdpPort}
HERMES_BROWSER_PROFILE=${profileDir}
EOF
      chown hermes:hermes /run/hermes-browser.env
      chmod 0640 /run/hermes-browser.env
    '';
  };

  # Ensure agent waits for CDP env (and prefers browser up, but does not hard-fail if browser restarts).
  systemd.services.hermes-agent = {
    after = [ "hermes-browser-env.service" ];
    wants = [ "hermes-browser-env.service" ];
  };

  systemd.services.hermes-browser = {
    description = "Hermes persistent Chromium (CDP on loopback)";
    wantedBy = [ "multi-user.target" ];
    after = [
      "network-online.target"
      "hermes-browser-env.service"
    ];
    wants = [
      "network-online.target"
      "hermes-browser-env.service"
    ];

    serviceConfig = {
      Type = "simple";
      User = "hermes";
      Group = "hermes";
      Restart = "on-failure";
      RestartSec = 5;
      MemoryMax = "2G";
      TimeoutStartSec = 60;
      StandardOutput = "append:/var/lib/hermes/browser-logs/chromium.stdout";
      StandardError = "append:/var/lib/hermes/browser-logs/chromium.stderr";
    };

    environment = {
      HOME = "/var/lib/hermes/home";
      XDG_CONFIG_HOME = "/var/lib/hermes/home/.config";
      XDG_CACHE_HOME = "/var/lib/hermes/home/.cache";
      DISPLAY = display;
    };

    script = ''
      set -euo pipefail
      mkdir -p ${profileDir} /var/lib/hermes/home /var/lib/hermes/browser-logs

      rm -f /tmp/.X${displayNum}-lock /tmp/.X11-unix/X${displayNum} || true

      ${pkgs.xorg.xvfb}/bin/Xvfb ${display} -screen 0 1400x900x24 -ac +extension GLX +render -noreset &
      xvfb_pid=$!
      trap 'kill $xvfb_pid 2>/dev/null || true' EXIT
      sleep 1

      exec ${pkgs.chromium}/bin/chromium \
        --user-data-dir=${profileDir} \
        --remote-debugging-address=${cdpAddr} \
        --remote-debugging-port=${toString cdpPort} \
        --no-first-run \
        --no-default-browser-check \
        --disable-dev-shm-usage \
        --disable-gpu \
        --window-size=1400,900 \
        --disable-features=TranslateUI \
        about:blank
    '';
  };
}
