# Site identity + resource caps for Hermes. Single source of truth for
# paths, context window, and RAM/CPU limits — gateway (container) and
# WebUI (host systemd, in-process agent) consume the same numbers.
#
# What this file is NOT anymore:
#   - PATH maps / toolbox buildEnv  → services.hermesPnP.toolbox (composer)
#   - container --env (mkDockerEnv) → composer toolbox/package modules
#   - browser CDP provisioning      → services.hermesPnP.browser (composer)
#
# Env injection rule (unchanged):
#   environment / environmentFiles → host-safe, lands in $HERMES_HOME/.env
#   container.extraOptions --env    → generated by the composer, not retyped
#   WebUI extraEnvironment         → agent.environment + host remaps + UI-only
{lib, ...}: let
  stateDir = "/var/lib/hermes";
  home = "${stateDir}/home";
  hermesHome = "${stateDir}/.hermes";
  workspace = "${stateDir}/workspace";
  data = "/data";
  containerHome = "/home/hermes";

  skills = {
    host = "${stateDir}/skills";
    container = "${data}/skills";
  };

  memoryRegistry = {
    host = "${stateDir}/memory/registry.json";
    container = "${data}/memory/registry.json";
  };

  gbrainAudit = {
    host = "${home}/.gbrain/audit";
    container = "${containerHome}/.gbrain/audit";
  };

  # Display + compressor window. model.context_length applies to the default
  # model only (grok-4.6); after a router hop the live catalog window wins.
  # Native fire is min(ratio × live window, this cap). 180k is the DeepSeek
  # ceiling; Grok on the 200k pin hits the <512k 75% floor first (~150k).
  contextLimit = 200000;
  compressionThreshold = 0.30;
  compressionThresholdTokens = 180000;

  # Both agent entrypoints (gateway container + WebUI process).
  resources = {
    memory = "2G";
    memoryDocker = "2g";
    cpus = 2;
    oomScoreAdjust = 500;
  };

  containerResourceOptions = [
    "--memory=${resources.memoryDocker}"
    "--memory-swap=${resources.memoryDocker}"
    "--cpus=${toString resources.cpus}"
    "--oom-score-adj=${toString resources.oomScoreAdjust}"
  ];

  systemdResourceConfig = {
    MemoryMax = resources.memory;
    CPUQuota = "${toString (resources.cpus * 100)}%";
    OOMScoreAdjust = resources.oomScoreAdjust;
  };

  hermes = {
    inherit
      stateDir
      home
      hermesHome
      workspace
      data
      containerHome
      skills
      memoryRegistry
      gbrainAudit
      contextLimit
      compressionThreshold
      compressionThresholdTokens
      resources
      containerResourceOptions
      systemdResourceConfig
      ;
  };
in {
  _module.args.hermes = hermes;
}
